siteTitle = "Jiri Krepl | blog"
siteDescr = "I am web developer with strong product sense. I like building software which makes world better. I am fluent in ES6 JavaScript."
siteAuthor = "Jiri Krepl"

siteTelegramUrl = ""
siteTwitterUrl = "https://twitter.com/JiriKrepl"
siteGithubUrl = "https://github.com/jirikrepl"
siteEmailUrl = "jiri.krepl@gmail.com"
siteRssUrl = ""
siteVkUrl = ""

googleAnalyticsId = "UA-39627237-4"

linkPrefix = ""